### ISSUE TITLE
[

### ISSUE THREAD

**Issue by geniiii** [chl0maki/megumii#6]
[

@oatmealine oatmealine reopened this 2 minutes ago
@geniiii
Collaborator Author
geniiii commented 2 minutes ago

[_****_](

#1. url
Duplicate of #

)
@geniiii
@oatmealine oatmealine closed this now
@oatmealine oatmealine reopened this now
@oatmealine oatmealine reopened this now
@oatmealine oatmealine closed this now
@oatmealine oatmealine reopened this now
@oatmealine oatmealine closed this now
@oatmealine oatmealine reopened this now
@geniiii
Collaborator Author
geniiii commented now

        ``
        @oatmealine oatmealine closed this 3 minutes ago
        @geniiii
        Collaborator Author
        geniiii commented 2 minutes ago

    tenor (4)
    @geniiii geniiii reopened this 2 minutes ago
    @geniiii geniiii closed this 2 minutes ago
    @geniiii geniiii reopened this 2 minutes ago
    @geniiii geniiii closed this 2 minutes ago
    @geniiii geniiii reopened this 2 minutes ago
    @geniiii geniiii closed this 2 minutes ago
    @geniiii
    Collaborator Author
    geniiii commented 2 minutes ago

    @chl0maki @ #4

    `[

    ### ****

    ](url)`
    @geniiii geniiii reopened this 2 minutes ago
    @oatmealine
    Collaborator
    oatmealine commented 2 minutes ago

    @oatmealine oatmealine closed this 2 minutes ago
    @oatmealine
    Collaborator
    oatmealine commented 2 minutes ago

    @oatmealine oatmealine reopened this 2 minutes ago
    @geniiii
    Collaborator Author
    geniiii commented 2 minutes ago

    [_****_](

    #1. url
    Duplicate of #

    )](google.com)
    @geniiii

_Originally posted by @oatmealine in https://github.com/chl0maki/megumii/issues/5#issuecomment-659561378_

**Comment by geniiii** [comment]
This is real

**Comment by chl0maki** [comment]
hi

**Comment by geniiii** [comment]
hi
